[package]
name = "babel_proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
rfd = "~0.14"
serde = "1.0.197"
serde_json = "~1.0"
sqlite = "0.34.0"
